<?php

use App\Models\User;

return [
    'permissions' => [
        'roles.view' => [
            'label' => 'Visor de roles',
            'description' => 'Permite consultar información de roles autorizados desde la navbar.',
            'route' => 'role-viewer.store',
            'icon' => 'roles',
            'scope' => 'application',
            'default_roles' => [],
        ],
        'videos.view' => [
            'label' => 'Ver vídeos de formación',
            'description' => 'Permite consultar los vídeos de formación de la aplicación.',
            'route' => 'videos',
            'icon' => 'videos',
            'scope' => 'application',
            'default_roles' => [],
        ],
        'reports.hr.view' => [
            'label' => 'Ver Informes HR',
            'description' => 'Permite consultar los informes internos de HR.',
            'route' => 'tools.informes',
            'icon' => 'reports',
            'scope' => 'application',
            'default_roles' => [],
        ],
        'reviews.view' => [
            'label' => 'Ver reseñas',
            'description' => 'Permite consultar y gestionar las reseñas de la aplicación.',
            'route' => 'reviews.index',
            'icon' => 'reviews',
            'scope' => 'application',
            'default_roles' => [],
        ],
        'reviews.google.manage' => [
            'label' => 'Gestionar conexión de Google Reviews',
            'description' => 'Permite gestionar desde el backoffice la conexión con Google Reviews.',
            'route' => 'backoffice.google-reviews-connection',
            'icon' => 'reviews',
            'scope' => 'backoffice',
            'default_roles' => [User::ROLE_ADMIN],
        ],
        'rankings.view' => [
            'label' => 'Ver rankings públicos',
            'description' => 'Permite consultar los rankings públicos de la aplicación.',
            'route' => 'leaderboard.sales',
            'icon' => 'rankings',
            'scope' => 'application',
            'default_roles' => [],
        ],
        'curricula.view' => [
            'label' => 'Analizar currículums',
            'description' => 'Permite analizar currículums, rankear candidatos y definir cuáles pasan a entrevista con sus puntos fuertes y débiles.',
            'route' => 'curriculums.index',
            'icon' => 'curriculums',
            'scope' => 'application',
            'default_roles' => [],
        ],
        'users.manage' => [
            'label' => 'Gestión de usuarios',
            'description' => 'Altas, edición de perfiles y seguimiento del equipo.',
            'route' => 'users.index',
            'icon' => 'users',
            'default_roles' => [User::ROLE_ADMIN],
        ],
        'dealerships.manage' => [
            'label' => 'Gestión de delegaciones',
            'description' => 'Consulta, crea y organiza las delegaciones disponibles.',
            'route' => 'dealerships.index',
            'icon' => 'dealership',
            'default_roles' => [User::ROLE_ADMIN],
        ],
        'zones.manage' => [
            'label' => 'Gestión de zonas',
            'description' => 'Agrupa delegaciones en zonas y controla su reparto.',
            'route' => 'admin.zones.index',
            'icon' => 'zones',
            'default_roles' => [User::ROLE_ADMIN],
        ],
        'contacts.manage' => [
            'label' => 'Gestión de contactos',
            'description' => 'Mantén los contactos externos que aparecen en la agenda.',
            'route' => 'admin.contacts.index',
            'icon' => 'contacts',
            'default_roles' => [User::ROLE_ADMIN],
        ],
        'ticket-tools.manage' => [
            'label' => 'Gestionar tipos de incidencia',
            'description' => 'Crea, edita y elimina los tipos de incidencia que se muestran al abrir un ticket.',
            'route' => 'admin.ticket-tools.index',
            'icon' => 'ticket-tools',
            'default_roles' => [User::ROLE_ADMIN],
        ],
        'backoffice.rankings.manage' => [
            'label' => 'Gestionar rankings',
            'description' => 'Permite acceder a Rankings en el backoffice y recargar los datos desde Salesforce.',
            'route' => 'backoffice.rankings',
            'icon' => 'rankings',
            'scope' => 'backoffice',
            'default_roles' => [User::ROLE_ADMIN],
        ],
        'tickets-it.assign' => [
            'label' => 'Asignar tickets IT',
            'description' => 'Permite asignar tickets a personas del equipo de informática.',
            'route' => 'tickets.assign',
            'icon' => 'ticket-tools',
            'scope' => 'application',
            'default_roles' => [],
        ],
        'tickets-it.reports.view' => [
            'label' => 'Ver informes de tickets IT',
            'description' => 'Permite consultar los informes y métricas de tickets IT.',
            'route' => 'tickets.reports',
            'icon' => 'ticket-tools',
            'scope' => 'application',
            'default_roles' => [],
        ],
        'backoffice.tickets-it-recipients.manage' => [
            'label' => 'Gestionar destinatarios de avisos de Tickets IT',
            'description' => 'Permite acceder al backoffice y gestionar los destinatarios de los avisos enviados al crear nuevos tickets IT.',
            'route' => 'backoffice.tickets-it-recipients',
            'icon' => 'ticket-tools',
            'scope' => 'backoffice',
            'default_roles' => [User::ROLE_ADMIN],
        ],
        'magazine.manage' => [
            'label' => 'Gestión de la revista mensual',
            'description' => 'Publica la edición mensual y actualiza la portada visible.',
            'route' => 'admin.magazine.edit',
            'icon' => 'magazine',
            'default_roles' => [User::ROLE_ADMIN],
        ],
        'bulletin.manage' => [
            'label' => 'Gestión del tablón',
            'description' => 'Publica avisos internos visibles para toda la plantilla.',
            'route' => 'admin.tablon.index',
            'icon' => 'bulletin',
            'default_roles' => [User::ROLE_ADMIN],
        ],
        'notifications.manage' => [
            'label' => 'Gestión de notificaciones',
            'description' => 'Envía avisos destacados a los roles que elijas.',
            'route' => 'admin.notifications.create',
            'icon' => 'notifications',
            'default_roles' => [User::ROLE_ADMIN],
        ],
        'chat-retention-holds.manage' => [
            'label' => 'Conservación excepcional de conversación del chat',
            'description' => 'Bloquea conversaciones o usuarios para que no entren en la purga automática.',
            'route' => 'admin.chat-retention-holds.index',
            'icon' => 'chat-retention-hold',
            'default_roles' => [User::ROLE_ADMIN],
        ],
        'conversation-access.manage' => [
            'label' => 'Acceso justificado a conversaciones',
            'description' => 'Solicita acceso temporal y auditado a conversaciones ajenas.',
            'route' => 'admin.conversation-access.index',
            'icon' => 'conversation-access',
            'default_roles' => [User::ROLE_ADMIN],
        ],
        'chat-groups.manage' => [
            'label' => 'Gestión de grupos del chat',
            'description' => 'Crea, edita y elimina los grupos internos del chat.',
            'route' => 'admin.chat-groups.index',
            'icon' => 'chat-groups',
            'default_roles' => [User::ROLE_ADMIN],
        ],
    ],
];
